language: cpp
os: linux
dist: focal

addons:
  sonarcloud:
    organization: "utilforever-github"
    token:
      secure: "WCmV8d5MDCtL+dqpzdRMNYL7/I6FzEAihaFtUjypMwJCLzBVkKSZYAE7XnLQiLZrlx9O5qYEnqRGEI0O1MvP2RrrSDDkz+5xCm0jAP9v2ymkMQ92brYgKQqZUHcoUuAzb+qn2nHFqTuyZ7aazzXp4ZhRYUprbRai/oANcI/RwHdqTOS0P51RkG/kPmuL54QbZ/K3ijx1L+TtID2B3BwRrd74EAGcaNkwPwtda+eK0ZJN4Y3jJ6HYvimXBFYPzRigYxrU1BkKp40444cUaL4enFwTRhim0WP1T8kaZVLqjlK1EXGcBYhNu/OiUOlrIEz8RjEUHLjvtBJArPP4NMlD5Z9NrA43E4EHYmg6b/FuFHu3ia5Dn4Ovg1SxaXB3EaRMctx5bAwO9gztiUx/DW7GGFP/xFxDoo/KbOtv4nYjEGzlr01KTSxeKVmftYC/XQ0K+tAqtPTH1WXrQ6LENRLmRyuQDERFyBpm/J5RCDkxKJpERso5EPHu+w/vjHV9E5EW+LVAC9OmbHdvRwppcNuq8jGXPjqRo3g8SaqKDng/4xUgTJrXk/f+d/Nub1Sc9ICfnPJxz9Ln5KDDi7jA2lGfC5fmHDKCHlH9Zubbx3q9L0QkGYy4N6NhRvQTXjSKXDF2mYGVNYjtBrSkKBpAeDpHazje5tODNqeDMF2ILpKJeNo="

script:
  # Install packages
  - sudo apt-get install -yq gcovr ggcov lcov curl
  # Configure build
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_COVERAGE=ON
  # Wraps the compilation with the Build Wrapper to generate configuration
  # (used later by the SonarQube Scanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir ../bw-output make all
  # Execute some tests
  - lcov --gcov-tool /usr/bin/gcov -c -i -d Tests/UnitTests -o base.info
  - bin/UnitTests
  - lcov --gcov-tool /usr/bin/gcov -c -d Tests/UnitTests -o test.info
  - lcov --gcov-tool /usr/bin/gcov -a base.info -a test.info -o coverage.info
  - lcov --gcov-tool /usr/bin/gcov -r coverage.info '*/Extensions/*' -o coverage.info
  - lcov --gcov-tool /usr/bin/gcov -r coverage.info '*/Includes/*' -o coverage.info
  - lcov --gcov-tool /usr/bin/gcov -r coverage.info '*/Libraries/*' -o coverage.info
  - lcov --gcov-tool /usr/bin/gcov -l coverage.info
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - cd ..
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'